# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d34d193687c5d4948b6137488aae3ca9929a7a6bebc4edc85935b9be7ca95ed0eaf2563990004d5751dbc9cf3ff20511ac698cccb39473c00ef412b79852550c

test:
  secret_key_base: 7666756278036cf0dbc2189b5f4b3c8471d9539049016840a7448e46f9f391bc7a85b9a1f2cbf356bfa385e0b2a415569baf5f23cbe4c194ecb8e9d15c8a19aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
